# Generated by Django 3.1.7 on 2021-03-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210313_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='status',
        ),
        migrations.AddField(
            model_name='fighter',
            name='fire_status',
            field=models.CharField(choices=[('P', 'Fire is present'), ('N', 'Fire is not present')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='fighter',
            name='operation_status',
            field=models.CharField(choices=[('O', 'Agent is operational'), ('N', 'Agent is not operational')], default='O', max_length=1),
        ),
    ]
